let user = prompt ('ismingizni kiriting');
alert (user);
console.log (user);
let familiya = prompt ('familiyangizni kiriting');
alert (familiya);
console.log (familiya);
let age = prompt ('yoshingizni kiriting');
alert (age);
console.log (age);
let fan = prompt ('yoqtirgan faningizni yozing');
alert (fan);
console.log (fan);
let locotion = prompt ('yashaydigan tumaningizni kiriting');
alert (locotion);
console.log (locotion);
alert    ('malumotingizni kiritganingoiz uchiun tashakkur');